# Generated by Django 4.2.4 on 2023-09-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTerceraEntrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosNuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('largo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductosUsados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('largo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='celular',
            field=models.IntegerField(),
        ),
    ]
